import { FC } from "react";
import Head from "next/head";
import styles from "./MainLayout.module.css";
import { Navbar } from "../Navbar";

type props = {
  children : React.ReactNode;
}

export const MainLayout = ( props:props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>{props.children}</main>
    </div>
  );
};
